import Rule110.CookLen6AppendantSim

namespace Rule110

/-! Auto-generated: c2SimRun 390 len6TruePhasedSupportInit as a literal.
    Proved correct by native_decide in `len6Evolved390_correct`. -/

def len6Evolved390 : List Bool := #[
    true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, true, true, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false,
    false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false,
    false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false,
    true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, true, true, true, true, true, true, false, true, true, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true,
    true, true, false, false, false, true, false, false, true, true, false, false, true, true, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true,
    true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true,
    true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false,
    false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, true,
    true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true,
    true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, false, false, true, true, true, true, true, false, true, false, true, true, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true,
    true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false,
    false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false,
    false, true, true, false, true, false, false, false, true, true, false, true, false, false, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true,
    false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true,
    true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false,
    false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false,
    true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true,
    false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true,
    false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true,
    true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false,
    false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false,
    true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true,
    true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true,
    false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true,
    false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true,
    false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true,
    true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false,
    false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false,
    true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true,
    true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true,
    false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true,
    false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true,
    false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true,
    true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false,
    false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false,
    true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, false, true, true, true, false, false, true, true, false, false, false, false,
    true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true,
    true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, false, false, true, true, false, true, true, true, true, true, false, false, false, true, true
  ].toList

@[simp] theorem len6Evolved390_length : len6Evolved390.length = c2SimBound := by
  native_decide

theorem len6Evolved390_correct :
    len6Evolved390 = c2SimRun 390 len6TruePhasedSupportInit := by
  native_decide

end Rule110
